### ISSUE TITLE
Leveling the chat code up

### ISSUE THREAD

**Issue by amaury95** [revision-team/profito#3]
### **_For this assignment we need to get the major functionality of the messages code._** 

We need to have the following functionalities:

1. Message interface must be created with two fields. An identifier "key" of type string and a "message" field of type string.
2. Contacts (The left sidebar) should use a different collection of messages. This collections should be handdled by useStates hook and should be an initial empty array of Messages.
3. The typing area "textbox" must be functional. Meaning that when you type and click enter, the conversation with the selected contact must be updated with a new Message.
3. On select a contact: the conversation panel should update with the array of Messages.

**Comment by instantwpuserwin** [comment]
Please review: Leveling the chat code up.

**Comment by amaury95** [comment]
The next assignment will be making functional the buttons above the input element. Send file, open camera, send emoji, etc...

**Comment by instantwpuserwin** [comment]
Hey,

I need some guidance:
For example, 
1. what npm libraries should be used? Audio, imogi
2. Image Posting: Can I use express to setup a post service? 

I can select my own libaries or setup express server, but then, was not sure how to proceed.

Please advise or guide.

Thanks

**Comment by amaury95** [comment]
No, don’t submit anything yet, just if some file is selected and posted, show it in the specific chat.

**Comment by instantwpuserwin** [comment]
"just if some file is selected and posted, show it in the specific chat."
Ok. I can do image upload this way.

But what about imojis, audio record, photo capture etc.
Please advise.

**Comment by amaury95** [comment]
Same thing, just show it in the chat

**Comment by instantwpuserwin** [comment]
Apologize, did not understand fully.

For each click, on respetive buttons, just a simple handler is enough?
for example, when camera icon is clicked,  chat should show "camera clicked". Like that? Simple handlers?

**Comment by amaury95** [comment]
No, you should show the normal behavior in the client side:

If a camera is clicked, you should show an option to take a photo or select one from a file...

If you click in emojis, you should show a component showing the available emojis and if you select one of them it should be shown in screen

**Comment by instantwpuserwin** [comment]
Emojis: Can I install a library? Like https://github.com/ealush/emoji-picker-react?

"If a camera is clicked, you should show an option to take a photo or select one from a file..."
But to show an image posted, I need to post it to a server? And then show? Can I use cloudinary to store images? Or store locally in a folder?

**Comment by amaury95** [comment]
Yes, of course you can install packages, and about the image, do whatever you feel comfortable with...

**Comment by instantwpuserwin** [comment]
ok. thanks for clearing
